############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Build"
pageRef = "/build"
weight = 2

[[main]]
name = "FAQ"
pageRef = "/tikolyfaq"
weight = 3

[[main]]
name = "About"
pageRef = "/about"
weight = 4

#[[main]]
#weight = 4
#name = "Pages"

#[[main]]
#parent = "Pages"
#name = "Blog"
#pageRef = "/blog"

#[[main]]
#parent = "Pages"
#name = "Contact"
#pageRef = "/contact"

#[[main]]
#parent = "Pages"
#name = "Authors"
#pageRef = "/authors"

#[[main]]
#parent = "Pages"
#name = "Categories"
#pageRef = "/categories"

#[[main]]
#parent = "Pages"
#name = "404 Page"
#pageRef = "/404"


# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1

[[footer]]
name = "FAQ"
pageRef = "/tikolyfaq"
weight = 2

[[footer]]
name = "Privacy Policy"
href = "/privacy-policy"
weight = 3
